// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

#include "game/scenes/invasion/infra/animation_strip_registry.hpp"
#include <cstdint>

namespace components {

struct AnimationUnpausable {
    uint16_t tick_counter = 0;
    uint16_t ticks_per_frame = 0;
    uint8_t cur_frame = 0;
    infra::AnimationStripID strip_id = 0;

    bool operator==(const AnimationUnpausable &) const = default;
};

}
