// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

#include "framework/tick.hpp"
#include "game/scenes/invasion/infra/callback_registry.hpp"

namespace components {

struct CallbackOnTimeoutUnpausable {
    framework::Tick invoke_on_tick = 0;
    infra::CallbackID callback = 0;

    bool operator==(const CallbackOnTimeoutUnpausable &) const = default;
};

}
