// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

#include "game/scenes/invasion/infra/callback_registry.hpp"
#include <cstdint>

namespace components {

struct CallbackOnTimeoutUnpausable {
    uint64_t invoke_on_tick = 0;
    infra::CallbackID callback = 0;

    bool operator==(const CallbackOnTimeoutUnpausable &) const = default;
};

}
