// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

namespace components {

struct CollisionActive {
    float hitbox_offset_x = 0.0F;
    float hitbox_offset_y = 0.0F;
    float hitbox_w = 0.0F;
    float hitbox_h = 0.0F;

    bool operator==(const CollisionActive &) const = default;
};

}
