// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

#include "game/scenes/invasion/infra/callback_registry.hpp"

namespace components {

struct DamageCallback {
    infra::CallbackID callback = 0;

    bool operator==(const DamageCallback &) const = default;
};

}
