// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

#include "game/scenes/invasion/components/damage_type_enum.hpp"
#include <cstdint>

namespace components {

struct Damage {
    DamageTypeSet type = 0;
    uint8_t amount = 0;

    bool operator==(const Damage &) const = default;
};

}
