// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

#include "game/scenes/invasion/components/damage_type_enum.hpp"
#include <cstdint>

namespace components {

struct Hitpoints {
    DamageTypeSet susceptible_to = 0;
    uint8_t cur_hitpoints = 0;

    bool operator==(const Hitpoints &) const = default;
};

}
