// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

#include <cstdint>

namespace components {

struct HUD {
    uint32_t score = 0;
    uint32_t high_score = 0;
    uint8_t remaining_lives = 0;

    bool operator==(const HUD &) const = default;
};

}
