// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

#include "game/scenes/invasion/infra/animation_strip_registry.hpp"
#include <cstdint>

namespace components {

struct InvaderAnimation {
    uint8_t cur_frame = 0;
    infra::AnimationStripID strip_id = 0;

    bool operator==(const InvaderAnimation &) const = default;
};

}
