// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

#include "game/scenes/invasion/infra/callback_registry.hpp"
#include <cstdint>

namespace components {

struct PlayerAttack {
    uint32_t ticks_per_attack = 0;
    uint32_t tick_counter = 0;
    infra::CallbackID callback = 0;

    bool operator==(const PlayerAttack &) const = default;
};

}
