// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

#include <cstdint>

namespace components {

struct PlayerMovement {
    uint8_t x_speed = 0;

    bool operator==(const PlayerMovement &) const = default;
};

}
