// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

#include <cstdint>

namespace components {

struct PositionFollowing {
    uint32_t leader = 0;
    float x_offset = 0.0F;
    float y_offset = 0.0F;

    bool operator==(const PositionFollowing &) const = default;
};

}
