// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off

#include "game/scenes/invasion/components/animation.hpp"
#include "game/scenes/invasion/components/animation_unpausable.hpp"
#include "game/scenes/invasion/components/callback_on_timeout.hpp"
#include "game/scenes/invasion/components/callback_on_timeout_unpausable.hpp"
#include "game/scenes/invasion/components/collision_active.hpp"
#include "game/scenes/invasion/components/collision_callback.hpp"
#include "game/scenes/invasion/components/collision_passive.hpp"
#include "game/scenes/invasion/components/damage.hpp"
#include "game/scenes/invasion/components/damage_callback.hpp"
#include "game/scenes/invasion/components/deletion_callback.hpp"
#include "game/scenes/invasion/components/game_over.hpp"
#include "game/scenes/invasion/components/hitpoints.hpp"
#include "game/scenes/invasion/components/hud.hpp"
#include "game/scenes/invasion/components/invader_animation.hpp"
#include "game/scenes/invasion/components/invader_orchestration_state.hpp"
#include "game/scenes/invasion/components/orchestrated_invader.hpp"
#include "game/scenes/invasion/components/pause.hpp"
#include "game/scenes/invasion/components/player_attack.hpp"
#include "game/scenes/invasion/components/player_movement.hpp"
#include "game/scenes/invasion/components/position.hpp"
#include "game/scenes/invasion/components/position_following.hpp"
#include "game/scenes/invasion/components/sprite.hpp"
#include "game/scenes/invasion/components/to_be_deleted.hpp"
#include "game/scenes/invasion/components/ttl.hpp"
#include "game/scenes/invasion/components/velocity.hpp"

#include <entt.hpp>
#include <lua.h>
#include <LuaBridge/LuaBridge.h>

namespace components {

void register_components(entt::registry &ecs, lua_State *L) {
    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction("create", [&ecs]() -> uint32_t { return entt::to_integral(ecs.create()); })
        .addFunction(
            "clearAll",
            [&ecs]() {
                ecs.clear();
                ecs.ctx().clear();
            }
        )
        .endNamespace();

  // Animation

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<Animation>("Animation")
        .addConstructor<void()>()
        .addProperty("tickCounter", &Animation::tick_counter, &Animation::tick_counter)
        .addProperty("ticksPerFrame", &Animation::ticks_per_frame, &Animation::ticks_per_frame)
        .addProperty("curFrame", &Animation::cur_frame, &Animation::cur_frame)
        .addProperty("stripID", &Animation::strip_id, &Animation::strip_id)
        .addProperty("playing", &Animation::playing, &Animation::playing)
        .addProperty("playReversed", &Animation::play_reversed, &Animation::play_reversed)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setAnimation",
            [&ecs](uint32_t entity_int, Animation component) {
                ecs.emplace_or_replace<Animation>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasAnimation",
            [&ecs](uint32_t entity_int) { return ecs.all_of<Animation>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getAnimation",
            [&ecs](uint32_t entity_int) { return ecs.get<Animation>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeAnimation",
            [&ecs](uint32_t entity_int) { ecs.remove<Animation>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // AnimationUnpausable

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<AnimationUnpausable>("AnimationUnpausable")
        .addConstructor<void()>()
        .addProperty("tickCounter", &AnimationUnpausable::tick_counter, &AnimationUnpausable::tick_counter)
        .addProperty("ticksPerFrame", &AnimationUnpausable::ticks_per_frame, &AnimationUnpausable::ticks_per_frame)
        .addProperty("curFrame", &AnimationUnpausable::cur_frame, &AnimationUnpausable::cur_frame)
        .addProperty("stripID", &AnimationUnpausable::strip_id, &AnimationUnpausable::strip_id)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setAnimationUnpausable",
            [&ecs](uint32_t entity_int, AnimationUnpausable component) {
                ecs.emplace_or_replace<AnimationUnpausable>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasAnimationUnpausable",
            [&ecs](uint32_t entity_int) { return ecs.all_of<AnimationUnpausable>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getAnimationUnpausable",
            [&ecs](uint32_t entity_int) { return ecs.get<AnimationUnpausable>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeAnimationUnpausable",
            [&ecs](uint32_t entity_int) { ecs.remove<AnimationUnpausable>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // CallbackOnTimeout

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<CallbackOnTimeout>("CallbackOnTimeout")
        .addConstructor<void()>()
        .addProperty("callback", &CallbackOnTimeout::callback, &CallbackOnTimeout::callback)
        .addProperty("timeoutTicks", &CallbackOnTimeout::timeout_ticks, &CallbackOnTimeout::timeout_ticks)
        .addProperty("tickCounter", &CallbackOnTimeout::tick_counter, &CallbackOnTimeout::tick_counter)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setCallbackOnTimeout",
            [&ecs](uint32_t entity_int, CallbackOnTimeout component) {
                ecs.emplace_or_replace<CallbackOnTimeout>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasCallbackOnTimeout",
            [&ecs](uint32_t entity_int) { return ecs.all_of<CallbackOnTimeout>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getCallbackOnTimeout",
            [&ecs](uint32_t entity_int) { return ecs.get<CallbackOnTimeout>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeCallbackOnTimeout",
            [&ecs](uint32_t entity_int) { ecs.remove<CallbackOnTimeout>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // CallbackOnTimeoutUnpausable

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<CallbackOnTimeoutUnpausable>("CallbackOnTimeoutUnpausable")
        .addConstructor<void()>()
        .addProperty("callback", &CallbackOnTimeoutUnpausable::callback, &CallbackOnTimeoutUnpausable::callback)
        .addProperty("timeoutTicks", &CallbackOnTimeoutUnpausable::timeout_ticks, &CallbackOnTimeoutUnpausable::timeout_ticks)
        .addProperty("tickCounter", &CallbackOnTimeoutUnpausable::tick_counter, &CallbackOnTimeoutUnpausable::tick_counter)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setCallbackOnTimeoutUnpausable",
            [&ecs](uint32_t entity_int, CallbackOnTimeoutUnpausable component) {
                ecs.emplace_or_replace<CallbackOnTimeoutUnpausable>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasCallbackOnTimeoutUnpausable",
            [&ecs](uint32_t entity_int) { return ecs.all_of<CallbackOnTimeoutUnpausable>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getCallbackOnTimeoutUnpausable",
            [&ecs](uint32_t entity_int) { return ecs.get<CallbackOnTimeoutUnpausable>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeCallbackOnTimeoutUnpausable",
            [&ecs](uint32_t entity_int) { ecs.remove<CallbackOnTimeoutUnpausable>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // CollisionActive

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<CollisionActive>("CollisionActive")
        .addConstructor<void()>()
        .addProperty("hitboxOffsetX", &CollisionActive::hitbox_offset_x, &CollisionActive::hitbox_offset_x)
        .addProperty("hitboxOffsetY", &CollisionActive::hitbox_offset_y, &CollisionActive::hitbox_offset_y)
        .addProperty("hitboxW", &CollisionActive::hitbox_w, &CollisionActive::hitbox_w)
        .addProperty("hitboxH", &CollisionActive::hitbox_h, &CollisionActive::hitbox_h)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setCollisionActive",
            [&ecs](uint32_t entity_int, CollisionActive component) {
                ecs.emplace_or_replace<CollisionActive>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasCollisionActive",
            [&ecs](uint32_t entity_int) { return ecs.all_of<CollisionActive>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getCollisionActive",
            [&ecs](uint32_t entity_int) { return ecs.get<CollisionActive>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeCollisionActive",
            [&ecs](uint32_t entity_int) { ecs.remove<CollisionActive>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // CollisionCallback

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<CollisionCallback>("CollisionCallback")
        .addConstructor<void()>()
        .addProperty("callback", &CollisionCallback::callback, &CollisionCallback::callback)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setCollisionCallback",
            [&ecs](uint32_t entity_int, CollisionCallback component) {
                ecs.emplace_or_replace<CollisionCallback>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasCollisionCallback",
            [&ecs](uint32_t entity_int) { return ecs.all_of<CollisionCallback>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getCollisionCallback",
            [&ecs](uint32_t entity_int) { return ecs.get<CollisionCallback>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeCollisionCallback",
            [&ecs](uint32_t entity_int) { ecs.remove<CollisionCallback>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // CollisionPassive

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<CollisionPassive>("CollisionPassive")
        .addConstructor<void()>()
        .addProperty("hitboxOffsetX", &CollisionPassive::hitbox_offset_x, &CollisionPassive::hitbox_offset_x)
        .addProperty("hitboxOffsetY", &CollisionPassive::hitbox_offset_y, &CollisionPassive::hitbox_offset_y)
        .addProperty("hitboxW", &CollisionPassive::hitbox_w, &CollisionPassive::hitbox_w)
        .addProperty("hitboxH", &CollisionPassive::hitbox_h, &CollisionPassive::hitbox_h)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setCollisionPassive",
            [&ecs](uint32_t entity_int, CollisionPassive component) {
                ecs.emplace_or_replace<CollisionPassive>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasCollisionPassive",
            [&ecs](uint32_t entity_int) { return ecs.all_of<CollisionPassive>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getCollisionPassive",
            [&ecs](uint32_t entity_int) { return ecs.get<CollisionPassive>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeCollisionPassive",
            [&ecs](uint32_t entity_int) { ecs.remove<CollisionPassive>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // Damage

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<Damage>("Damage")
        .addConstructor<void()>()
        .addProperty("type", &Damage::type, &Damage::type)
        .addProperty("amount", &Damage::amount, &Damage::amount)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setDamage",
            [&ecs](uint32_t entity_int, Damage component) {
                ecs.emplace_or_replace<Damage>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasDamage",
            [&ecs](uint32_t entity_int) { return ecs.all_of<Damage>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getDamage",
            [&ecs](uint32_t entity_int) { return ecs.get<Damage>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeDamage",
            [&ecs](uint32_t entity_int) { ecs.remove<Damage>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // DamageCallback

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<DamageCallback>("DamageCallback")
        .addConstructor<void()>()
        .addProperty("callback", &DamageCallback::callback, &DamageCallback::callback)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setDamageCallback",
            [&ecs](uint32_t entity_int, DamageCallback component) {
                ecs.emplace_or_replace<DamageCallback>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasDamageCallback",
            [&ecs](uint32_t entity_int) { return ecs.all_of<DamageCallback>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getDamageCallback",
            [&ecs](uint32_t entity_int) { return ecs.get<DamageCallback>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeDamageCallback",
            [&ecs](uint32_t entity_int) { ecs.remove<DamageCallback>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // DeletionCallback

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<DeletionCallback>("DeletionCallback")
        .addConstructor<void()>()
        .addProperty("callback", &DeletionCallback::callback, &DeletionCallback::callback)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setDeletionCallback",
            [&ecs](uint32_t entity_int, DeletionCallback component) {
                ecs.emplace_or_replace<DeletionCallback>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasDeletionCallback",
            [&ecs](uint32_t entity_int) { return ecs.all_of<DeletionCallback>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getDeletionCallback",
            [&ecs](uint32_t entity_int) { return ecs.get<DeletionCallback>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeDeletionCallback",
            [&ecs](uint32_t entity_int) { ecs.remove<DeletionCallback>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // GameOver

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setGameOver", [&ecs]() {
                if (!ecs.ctx().contains<GameOver>()) {
                    ecs.ctx().emplace<GameOver>();
                }
            }
        )
        .addFunction("hasGameOver", [&ecs]() { return ecs.ctx().contains<GameOver>(); })
        .addFunction("removeGameOver", [&ecs]() { ecs.ctx().erase<GameOver>(); })
        .endNamespace();

  // Hitpoints

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<Hitpoints>("Hitpoints")
        .addConstructor<void()>()
        .addProperty("susceptibleTo", &Hitpoints::susceptible_to, &Hitpoints::susceptible_to)
        .addProperty("curHitpoints", &Hitpoints::cur_hitpoints, &Hitpoints::cur_hitpoints)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setHitpoints",
            [&ecs](uint32_t entity_int, Hitpoints component) {
                ecs.emplace_or_replace<Hitpoints>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasHitpoints",
            [&ecs](uint32_t entity_int) { return ecs.all_of<Hitpoints>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getHitpoints",
            [&ecs](uint32_t entity_int) { return ecs.get<Hitpoints>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeHitpoints",
            [&ecs](uint32_t entity_int) { ecs.remove<Hitpoints>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // HUD

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<HUD>("HUD")
        .addConstructor<void()>()
        .addProperty("score", &HUD::score, &HUD::score)
        .addProperty("highScore", &HUD::high_score, &HUD::high_score)
        .addProperty("remainingLives", &HUD::remaining_lives, &HUD::remaining_lives)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setHUD", [&ecs](HUD component) { ecs.ctx().insert_or_assign<HUD>(std::move(component)); }
        )
        .addFunction("hasHUD", [&ecs]() { return ecs.ctx().contains<HUD>(); })
        .addFunction("getHUD", [&ecs]() { return ecs.ctx().get<HUD>(); })
        .addFunction("removeHUD", [&ecs]() { ecs.ctx().erase<HUD>(); })
        .endNamespace();

  // InvaderAnimation

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<InvaderAnimation>("InvaderAnimation")
        .addConstructor<void()>()
        .addProperty("curFrame", &InvaderAnimation::cur_frame, &InvaderAnimation::cur_frame)
        .addProperty("stripID", &InvaderAnimation::strip_id, &InvaderAnimation::strip_id)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setInvaderAnimation",
            [&ecs](uint32_t entity_int, InvaderAnimation component) {
                ecs.emplace_or_replace<InvaderAnimation>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasInvaderAnimation",
            [&ecs](uint32_t entity_int) { return ecs.all_of<InvaderAnimation>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getInvaderAnimation",
            [&ecs](uint32_t entity_int) { return ecs.get<InvaderAnimation>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeInvaderAnimation",
            [&ecs](uint32_t entity_int) { ecs.remove<InvaderAnimation>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // InvaderOrchestrationState

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<InvaderOrchestrationState>("InvaderOrchestrationState")
        .addConstructor<void()>()
        .addProperty("noInvadersCallback", &InvaderOrchestrationState::no_invaders_callback, &InvaderOrchestrationState::no_invaders_callback)
        .addProperty("shootCallback", &InvaderOrchestrationState::shoot_callback, &InvaderOrchestrationState::shoot_callback)
        .addProperty("touchdownCallback", &InvaderOrchestrationState::touchdown_callback, &InvaderOrchestrationState::touchdown_callback)
        .addProperty("baseTicksPerMove", &InvaderOrchestrationState::base_ticks_per_move, &InvaderOrchestrationState::base_ticks_per_move)
        .addProperty("tickCounter", &InvaderOrchestrationState::tick_counter, &InvaderOrchestrationState::tick_counter)
        .addProperty("xSpeed", &InvaderOrchestrationState::x_speed, &InvaderOrchestrationState::x_speed)
        .addProperty("ySpeed", &InvaderOrchestrationState::y_speed, &InvaderOrchestrationState::y_speed)
        .addProperty("lastInvaderXSpeed", &InvaderOrchestrationState::last_invader_x_speed, &InvaderOrchestrationState::last_invader_x_speed)
        .addProperty("lastInvaderYSpeed", &InvaderOrchestrationState::last_invader_y_speed, &InvaderOrchestrationState::last_invader_y_speed)
        .addProperty("ticksPerShot", &InvaderOrchestrationState::ticks_per_shot, &InvaderOrchestrationState::ticks_per_shot)
        .addProperty("shootTickCounter", &InvaderOrchestrationState::shoot_tick_counter, &InvaderOrchestrationState::shoot_tick_counter)
        .addProperty("curArp", &InvaderOrchestrationState::cur_arp, &InvaderOrchestrationState::cur_arp)
        .addProperty("movingLeft", &InvaderOrchestrationState::moving_left, &InvaderOrchestrationState::moving_left)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setInvaderOrchestrationState", [&ecs](InvaderOrchestrationState component) { ecs.ctx().insert_or_assign<InvaderOrchestrationState>(std::move(component)); }
        )
        .addFunction("hasInvaderOrchestrationState", [&ecs]() { return ecs.ctx().contains<InvaderOrchestrationState>(); })
        .addFunction("getInvaderOrchestrationState", [&ecs]() { return ecs.ctx().get<InvaderOrchestrationState>(); })
        .addFunction("removeInvaderOrchestrationState", [&ecs]() { ecs.ctx().erase<InvaderOrchestrationState>(); })
        .endNamespace();

  // OrchestratedInvader

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setOrchestratedInvader",
            [&ecs](uint32_t entity_int) {
                ecs.emplace_or_replace<OrchestratedInvader>(static_cast<entt::entity>(entity_int));
            }
        )
        .addFunction(
            "hasOrchestratedInvader",
            [&ecs](uint32_t entity_int) { return ecs.all_of<OrchestratedInvader>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeOrchestratedInvader",
            [&ecs](uint32_t entity_int) { ecs.remove<OrchestratedInvader>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // Pause

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setPause", [&ecs]() {
                if (!ecs.ctx().contains<Pause>()) {
                    ecs.ctx().emplace<Pause>();
                }
            }
        )
        .addFunction("hasPause", [&ecs]() { return ecs.ctx().contains<Pause>(); })
        .addFunction("removePause", [&ecs]() { ecs.ctx().erase<Pause>(); })
        .endNamespace();

  // PlayerAttack

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<PlayerAttack>("PlayerAttack")
        .addConstructor<void()>()
        .addProperty("ticksPerAttack", &PlayerAttack::ticks_per_attack, &PlayerAttack::ticks_per_attack)
        .addProperty("tickCounter", &PlayerAttack::tick_counter, &PlayerAttack::tick_counter)
        .addProperty("callback", &PlayerAttack::callback, &PlayerAttack::callback)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setPlayerAttack",
            [&ecs](uint32_t entity_int, PlayerAttack component) {
                ecs.emplace_or_replace<PlayerAttack>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasPlayerAttack",
            [&ecs](uint32_t entity_int) { return ecs.all_of<PlayerAttack>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getPlayerAttack",
            [&ecs](uint32_t entity_int) { return ecs.get<PlayerAttack>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removePlayerAttack",
            [&ecs](uint32_t entity_int) { ecs.remove<PlayerAttack>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // PlayerMovement

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<PlayerMovement>("PlayerMovement")
        .addConstructor<void()>()
        .addProperty("xSpeed", &PlayerMovement::x_speed, &PlayerMovement::x_speed)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setPlayerMovement",
            [&ecs](uint32_t entity_int, PlayerMovement component) {
                ecs.emplace_or_replace<PlayerMovement>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasPlayerMovement",
            [&ecs](uint32_t entity_int) { return ecs.all_of<PlayerMovement>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getPlayerMovement",
            [&ecs](uint32_t entity_int) { return ecs.get<PlayerMovement>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removePlayerMovement",
            [&ecs](uint32_t entity_int) { ecs.remove<PlayerMovement>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // Position

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<Position>("Position")
        .addConstructor<void()>()
        .addProperty("x", &Position::x, &Position::x)
        .addProperty("y", &Position::y, &Position::y)
        .addProperty("w", &Position::w, &Position::w)
        .addProperty("h", &Position::h, &Position::h)
        .addProperty("z", &Position::z, &Position::z)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setPosition",
            [&ecs](uint32_t entity_int, Position component) {
                ecs.emplace_or_replace<Position>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasPosition",
            [&ecs](uint32_t entity_int) { return ecs.all_of<Position>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getPosition",
            [&ecs](uint32_t entity_int) { return ecs.get<Position>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removePosition",
            [&ecs](uint32_t entity_int) { ecs.remove<Position>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // PositionFollowing

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<PositionFollowing>("PositionFollowing")
        .addConstructor<void()>()
        .addProperty("leader", &PositionFollowing::leader, &PositionFollowing::leader)
        .addProperty("xOffset", &PositionFollowing::x_offset, &PositionFollowing::x_offset)
        .addProperty("yOffset", &PositionFollowing::y_offset, &PositionFollowing::y_offset)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setPositionFollowing",
            [&ecs](uint32_t entity_int, PositionFollowing component) {
                ecs.emplace_or_replace<PositionFollowing>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasPositionFollowing",
            [&ecs](uint32_t entity_int) { return ecs.all_of<PositionFollowing>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getPositionFollowing",
            [&ecs](uint32_t entity_int) { return ecs.get<PositionFollowing>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removePositionFollowing",
            [&ecs](uint32_t entity_int) { ecs.remove<PositionFollowing>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // Sprite

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<Sprite>("Sprite")
        .addConstructor<void()>()
        .addProperty("srcID", &Sprite::src_id, &Sprite::src_id)
        .addProperty("srcX", &Sprite::src_x, &Sprite::src_x)
        .addProperty("srcY", &Sprite::src_y, &Sprite::src_y)
        .addProperty("srcW", &Sprite::src_w, &Sprite::src_w)
        .addProperty("srcH", &Sprite::src_h, &Sprite::src_h)
        .addProperty("dstW", &Sprite::dst_w, &Sprite::dst_w)
        .addProperty("dstH", &Sprite::dst_h, &Sprite::dst_h)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setSprite",
            [&ecs](uint32_t entity_int, Sprite component) {
                ecs.emplace_or_replace<Sprite>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasSprite",
            [&ecs](uint32_t entity_int) { return ecs.all_of<Sprite>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getSprite",
            [&ecs](uint32_t entity_int) { return ecs.get<Sprite>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeSprite",
            [&ecs](uint32_t entity_int) { ecs.remove<Sprite>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // ToBeDeleted

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setToBeDeleted",
            [&ecs](uint32_t entity_int) {
                ecs.emplace_or_replace<ToBeDeleted>(static_cast<entt::entity>(entity_int));
            }
        )
        .addFunction(
            "hasToBeDeleted",
            [&ecs](uint32_t entity_int) { return ecs.all_of<ToBeDeleted>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeToBeDeleted",
            [&ecs](uint32_t entity_int) { ecs.remove<ToBeDeleted>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // TTL

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<TTL>("TTL")
        .addConstructor<void()>()
        .addProperty("ticksToLive", &TTL::ticks_to_live, &TTL::ticks_to_live)
        .addProperty("tickCounter", &TTL::tick_counter, &TTL::tick_counter)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setTTL",
            [&ecs](uint32_t entity_int, TTL component) {
                ecs.emplace_or_replace<TTL>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasTTL",
            [&ecs](uint32_t entity_int) { return ecs.all_of<TTL>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getTTL",
            [&ecs](uint32_t entity_int) { return ecs.get<TTL>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeTTL",
            [&ecs](uint32_t entity_int) { ecs.remove<TTL>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();

  // Velocity

    luabridge::getGlobalNamespace(L)
        .beginNamespace("Components")
        .beginClass<Velocity>("Velocity")
        .addConstructor<void()>()
        .addProperty("x", &Velocity::x, &Velocity::x)
        .addProperty("y", &Velocity::y, &Velocity::y)
        .endClass()
        .endNamespace();

    luabridge::getGlobalNamespace(L)
        .beginNamespace("ECS")
        .addFunction(
            "setVelocity",
            [&ecs](uint32_t entity_int, Velocity component) {
                ecs.emplace_or_replace<Velocity>(static_cast<entt::entity>(entity_int), component);
            }
        )
        .addFunction(
            "hasVelocity",
            [&ecs](uint32_t entity_int) { return ecs.all_of<Velocity>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "getVelocity",
            [&ecs](uint32_t entity_int) { return ecs.get<Velocity>(static_cast<entt::entity>(entity_int)); }
        )
        .addFunction(
            "removeVelocity",
            [&ecs](uint32_t entity_int) { ecs.remove<Velocity>(static_cast<entt::entity>(entity_int)); }
        )
        .endNamespace();
}

}
