// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

#include <entt.hpp>
#include <lua.h>

namespace components {

void register_components(entt::registry &ecs, lua_State *L);

}
