// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

#include <cstdint>

namespace components {

struct TTL {
    uint64_t live_until_tick = 0;

    bool operator==(const TTL &) const = default;
};

}
