// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

#include <cstdint>

namespace components {

struct TTL {
    uint16_t ticks_to_live = 0;
    uint16_t tick_counter = 0;

    bool operator==(const TTL &) const = default;
};

}
