// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

#include "framework/tick.hpp"

namespace components {

struct TTL {
    framework::Tick live_until_tick = 0;

    bool operator==(const TTL &) const = default;
};

}
