// This file was generated by github.com/phonaputer/cmpgen. Do not edit!
// clang-format off
#pragma once

namespace components {

struct Velocity {
    float x = 0.0F;
    float y = 0.0F;

    bool operator==(const Velocity &) const = default;
};

}
